---

- name: Add JetBrains admin group
  group:
    name: jbadmin
    state: present

- name: Create JetBrains folder
  file:
    name: /opt/JetBrains
    owner: root
    group: jbadmin
    mode: 2775
    state: directory

- import_tasks: phpstorm.yml
  when: jetbrains is defined and jetbrains.php is defined and jetbrains.php.enable

- import_tasks: rubymine.yml
  when: jetbrains is defined and jetbrains.ruby is defined and jetbrains.ruby.enable

- import_tasks: intelliJ.yml
  when: jetbrains is defined and jetbrains.java is defined and jetbrains.java == "free"

