- name: "[RUBYMINE] Check if RubyMine {{ jetbrains.ruby.version }} is installed"
  stat:
    path: /opt/JetBrains/RubyMine-{{ jetbrains.ruby.version }}
  register: rubymine_dir

- name: "[RUBYMINE] Download RubyMine {{ jetbrains.ruby.version }}"
  get_url:
    url: https://download.jetbrains.com/ruby/RubyMine-{{ jetbrains.ruby.version }}.tar.gz
    dest: /tmp/rubymine.tar.gz
  when: not rubymine_dir.stat.exists
  register: rubymine_download

- name: "[RUBYMINE] Unpack RubyMine"
  unarchive:
    remote_src: yes
    src: /tmp/rubymine.tar.gz
    dest: /opt/JetBrains
    creates: /opt/JetBrains/RubyMine-{{ jetbrains.ruby.version }}
  when: rubymine_download is defined and rubymine_download.changed
  register: rubymine_unpack


- name: "[RUBYMINE] Ensure permissions"
  #shell: chmod -R g+sw /opt/JetBrains/RubyMine-{{ jetbrains.ruby.version }}
  file:
    path: /opt/JetBrains/RubyMine-{{ jetbrains.ruby.version }}
    owner: root
    group: jbadmin
    mode: ug+rw,g+s
    recurse: yes
    state: directory
#  when: rubymine_unpack.changed

- name: "[RUBYMINE] Install desktop entry"
  template:
    src: rubymine.desktop.j2
    dest: /usr/share/applications/jetbrains-rubymine.desktop
    owner: root
    group: jbadmin
    mode: 0644

- name: "[RUBYMINE] Remove downloaded package"
  file:
    path: /tmp/rubymine.tar.gz
    state: absent

- include_tasks: jetbrains-agent.yml
  when: jetbrains.ruby.version is version_compare('2018.1.3', '>')

- name: "[RUBYMINE] Configure JetBrains Agent"
  lineinfile:
    path: /opt/JetBrains/RubyMine-{{ jetbrains.ruby.version }}/bin/{{ item }}
    line: "-javaagent:/opt/JetBrains/jetbrains-agent/jetbrains-agent.jar"
    regexp: "^-javaagent:/opt/JetBrains/jetbrains-agent/jetbrains-agent.jar"
    owner: root
    group: jbadmin
    mode: 0664
    insertafter: EOF
    create: no
  when: jetbrains.agent.enable and jetbrains.ruby.version is version_compare('2018.1.3', '>')
  with_items:
    - rubymine64.vmoptions
    - rubymine.vmoptions
