---
jetbrains:
  ruby:
    enable: no
    version: 2020.1.1
  php:
    enable: no
    version: 2018.1.5
    build: 181.5281.19

  java:
    license: paid
    enable: no
    version: 2018.1.4
    build: 181.5087.20
  agent:
    enable: no
    url: https://static.hron.me/privcdn/jetbrains-agent-working.zip
