- name: Install NetworkManager and dependencies
  apt:
    name:
    - network-manager
    - dnsmasq
    state: present
  when: networkmanager is defined and networkmanager.enabled
  register: nm_pkg

- name: Install NetworkManager plugins
  apt:
    name: network-manager-{{ item }}
    install_recommends: no
  with_items:
  - "{{ networkmanager.plugins }}"
  when: networkmanager is defined and networkmanager.enabled

- name: Install NetworkManager GNOME plugins
  apt:
    name: network-manager-{{ item }}-gnome
  with_items:
  - "{{ networkmanager.plugins }}"
  when: networkmanager is defined and networkmanager.enabled and gui is defined
  notify: restart network-manager

- name: Set NetworkManager to manage wired devices
  ini_file:
    path: /etc/NetworkManager/NetworkManager.conf
    section: keyfile
    option: "unmanaged-devices"
    value: "*,except:type:wifi,except:type:wwan,except:type:ethernet"
  when: networkmanager is defined and networkmanager.enabled
  notify: restart network-manager

- name: Set NetworkManager to use DNSMasq
  ini_file:
    path: /etc/NetworkManager/NetworkManager.conf
    section: main
    option: dns
    value: dnsmasq
  when: networkmanager is defined and networkmanager.enabled
  notify: restart network-manager

- name: Set .wip as a valid TLD for localhost
  copy:
    dest: /etc/NetworkManager/dnsmasq.d/dnsmasq.conf
    content: address=/wip/127.0.0.1
  when: networkmanager is defined and networkmanager.enabled
  notify: restart network-manager

- name: Disable DNSMasq service, NM manages it
  service:
    enabled: no
    name: dnsmasq
    state: stopped
  when: networkmanager is defined and networkmanager.enabled

- name: Redirect resolv.conf to NetworkManager
  file:
    src: /var/run/NetworkManager/resolv.conf
    dest: /etc/resolv.conf
  when: networkmanager is defined and networkmanager.enabled and nm_pkg.changed

- name: Disable SystemD Resolver service
  service:
    enabled: no
    name: systemd-resolved
    state: stopped
  when: networkmanager is defined and networkmanager.enabled


- name: Enable NetworkManager
  service:
    enabled: yes
    name: network-manager
  when: networkmanager is defined and networkmanager.enabled
