- name: Install NetworkManager and dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - network-manager
    - dnsmasq
  when: networkmanager is defined and networkmanager.enabled

- name: Install NetworkManager plugins
  apt:
    name: network-manager-{{ item }}
    install_recommends: no
  with_items:
  - "{{ networkmanager.plugins }}"
  when: networkmanager is defined and networkmanager.enabled

- name: Install NetworkManager GNOME plugins
  apt:
    name: network-manager-{{ item }}-gnome
  with_items:
  - "{{ networkmanager.plugins }}"
  when: networkmanager is defined and networkmanager.enabled and gui is defined

- name: Set NetworkManager to manage wired devices
  ini_file:
    path: /etc/NetworkManager/NetworkManager.conf
    section: keyfile
    option: "unmanaged-devices"
    value: "*,except:type:wifi,except:type:wwan,except:type:ethernet"

- name: Set NetworkManager to use DNSMasq
  ini_file:
    path: /etc/NetworkManager/NetworkManager.conf
    section: main
    option: dns
    value: dnsmasq


- name: Enable NetworkManager
  service:
    enabled: yes
    name: network-manager
    state: restarted

- name: Disable DNSMasq service, NM manages it
  service:
    enabled: no
    name: dnsmasq
    state: stopped
