---
- name: Add Chrome APT repo
  apt_repository:
    repo: "deb  {{ '[arch=amd64]' if  ansible_architecture == 'x86_64' else '' }} https://dl.google.com/linux/chrome/deb/ stable main"
    state: present
    filename: google-chrome

- name: Add Chrome keys
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ item }}"
  with_items:
    - 640DB551
    - 997C215E
    - 7721F63BD38B4796

- name: Install Google Chrome
  apt:
    update_cache: yes
    name: google-chrome-stable
    state: latest
