---
- name: Add TeamViewer APT key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ item }}"
  with_items:
    - EF423EF772DB573C
    - C5E224500C1289C0

- name: Add TeamViewer APT repository 
  apt_repository:
    repo: "deb http://linux.teamviewer.com/deb {{ item.dist }} {{ item.group }}"
    filename: teamviewer
    state: present
  with_items:
    - dist: stable
      group: main

- name: Install TeamViewer
  apt:
    update_cache: yes
    deb: https://download.teamviewer.com/download/teamviewer_i386.deb
    state: present

