---
- name: Install Ansible PPA Key
  apt_key:
    id: 7BB9C367
    keyserver: keyserver.ubuntu.com

- name: Install Ansible PPA repo
  apt_repository:
    repo: ppa:ansible/ansible


- name: Install Ansible
  apt:
    update_cache: yes
    name: ansible
    state: latest
