---

- name: Check if Messenger is installed
  stat:
    path: /usr/local/bin/caprine
  register: msngr_bin

- name: Download DEB
  get_url:
    #url: https://github.com/aluxian/Messenger-for-Desktop/releases/download/v{{ messenger.version }}/messengerfordesktop-{{ messenger.version }}-linux-amd64.deb
    url: https://github.com/sindresorhus/caprine/releases/download/v{{ messenger.version }}/caprine_{{ messenger.version }}_amd64.deb
    dest: /tmp/messenger.deb
  when: not msngr_bin.stat.exists

- name: Install DEB
  apt:
    deb: /tmp/messenger.deb
    state: present
  when: not msngr_bin.stat.exists
