- name: Add Ubuntu Mate Dev PPA
  apt_repository:
    repo: ubuntu-mate-dev/{{ ansible_distribution_release }}-mate
    state: present
  when: (gui is defined and gui.desktop == "mate" and ( ansible_distribution_version < 16.04 or ( gui.mate is defined and gui.mate.experimental is defined )))
 
- name: Install MATE Desktop environment
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: present
  with_items:
    - atril
    - brasero
    - caja-admin
    - caja-open-terminal
    - caja-seahorse
    - caja-sendto
    - caja-wallpaper
    - cheese
    - deja-dup
    - ffmpegthumbnailer
    - fonts-liberation
    - gdebi
    - gnome-disk-utility
    - hplip
    - ideviceinstaller
    - ifuse
    - indicator-session
    - libreoffice-calc
    - libreoffice-gnome
    - libreoffice-writer
    - lightdm-settings
    - mate-calc
    - mate-sensors-applet
    - mate-system-monitor
    - mate-tweak
    - mate-window-buttons-applet
    - mate-window-menu-applet
    - mate-window-title-applet
    - network-manager-gnome
    - pluma
    - pm-utils
    - rhythmbox
    - seahorse
    - thunderbird-gnome-support
    - transmission-gtk
    - ubuntu-mate-artwork
    - ubuntu-mate-core
    - ubuntu-mate-wallpapers-xenial

- name: Enable LightDM Service
  service:
    name: lightdm
    enabled: yes
    state: started
